// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lnpzhckquzqrsrybwftf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxucHpoY2txdXpxcnNyeWJ3ZnRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNjQ2ODYsImV4cCI6MjA3MTY0MDY4Nn0.Pai9P0jSMX5U911oTFbNlXFT8AgCWGKaEoW9vgGnNB8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});